# Generated by Django 3.0.5 on 2020-04-24 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Postava',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vytvoreno', models.DateTimeField(blank=True, null=True)),
                ('jmeno', models.CharField(max_length=15, null=True)),
                ('prijmeni', models.CharField(max_length=25, null=True)),
                ('datum_narozeni', models.DateField(null=True)),
                ('narodnost', models.CharField(default='Česká', max_length=20)),
                ('nabozenstvi', models.CharField(max_length=20, null=True)),
                ('politika', models.CharField(max_length=20, null=True)),
                ('vzdelani', models.CharField(max_length=50, null=True)),
                ('hobby', models.CharField(max_length=50, null=True)),
                ('bio', models.TextField(null=True)),
                ('majitel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Postavy',
            },
        ),
        migrations.CreateModel(
            name='Uzivatel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=50, null=True)),
                ('heslo', models.CharField(max_length=50, null=True)),
                ('nick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('postavy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloxov.Postava')),
            ],
            options={
                'verbose_name_plural': 'Uzivatele',
            },
        ),
        migrations.CreateModel(
            name='Clanek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulek', models.CharField(max_length=100)),
                ('obsah', models.TextField()),
                ('vytvoreno', models.DateTimeField(default=django.utils.timezone.now)),
                ('publikovano', models.DateTimeField(blank=True, null=True)),
                ('kategorie', models.IntegerField(default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Clanky',
            },
        ),
    ]
