# Generated by Django 3.0.5 on 2020-04-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloxov', '0002_auto_20200424_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postava',
            old_name='datum_narozeni',
            new_name='narozeni',
        ),
        migrations.AlterField(
            model_name='postava',
            name='jmeno',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='postava',
            name='prijmeni',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
