# Generated by Django 3.0.5 on 2020-04-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloxov', '0003_auto_20200424_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postava',
            name='bio',
            field=models.TextField(null=True, verbose_name='Životopis'),
        ),
        migrations.AlterField(
            model_name='postava',
            name='hobby',
            field=models.CharField(max_length=50, null=True, verbose_name='Koníčky'),
        ),
        migrations.AlterField(
            model_name='postava',
            name='jmeno',
            field=models.CharField(max_length=30, null=True, verbose_name='Křestní jméno'),
        ),
        migrations.AlterField(
            model_name='postava',
            name='nabozenstvi',
            field=models.CharField(max_length=20, null=True, verbose_name='Vyznání'),
        ),
        migrations.AlterField(
            model_name='postava',
            name='narodnost',
            field=models.CharField(default='Česká', max_length=20, verbose_name='Národnost'),
        ),
        migrations.AlterField(
            model_name='postava',
            name='narozeni',
            field=models.DateField(null=True, verbose_name='Datum narození'),
        ),
        migrations.AlterField(
            model_name='postava',
            name='politika',
            field=models.CharField(max_length=20, null=True, verbose_name='Politická orientace'),
        ),
        migrations.AlterField(
            model_name='postava',
            name='prijmeni',
            field=models.CharField(max_length=50, null=True, verbose_name='Příjmení'),
        ),
        migrations.AlterField(
            model_name='postava',
            name='vzdelani',
            field=models.CharField(max_length=50, null=True, verbose_name='Vzdělání'),
        ),
    ]
