# Generated by Django 3.0.5 on 2020-04-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloxov', '0004_auto_20200427_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanek',
            name='kategorie',
            field=models.IntegerField(choices=[(1, 'Bazoš'), (2, 'BloxNews'), (3, 'InstaBlox'), (4, 'Internet'), (5, 'Uřední deska')], default=1),
        ),
    ]
