# Generated by Django 3.0.5 on 2020-04-27 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloxov', '0005_auto_20200427_1101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uzivatel',
        ),
    ]
