# Generated by Django 3.0.5 on 2020-04-27 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloxov', '0006_delete_uzivatel'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanek',
            name='postava',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bloxov.Postava'),
        ),
        migrations.AddField(
            model_name='postava',
            name='cele_jmeno',
            field=models.CharField(max_length=81, null=True),
        ),
    ]
