# Generated by Django 3.0.5 on 2020-04-28 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloxov', '0007_auto_20200427_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanek',
            name='postava',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bloxov.Postava', verbose_name='Postava jako autor'),
        ),
    ]
