# Generated by Django 3.0.5 on 2020-04-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloxov', '0009_clanek_obrazek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanek',
            name='kategorie',
            field=models.IntegerField(choices=[(1, 'Bazoš'), (2, 'BloxNews'), (3, 'InstaBlox'), (4, 'Internet'), (5, 'Úřední deska')], default=1),
        ),
    ]
