# Generated by Django 3.0.5 on 2020-05-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloxov', '0010_auto_20200429_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='postava',
            name='jazyky',
            field=models.CharField(max_length=70, null=True, verbose_name='Jazyky'),
        ),
        migrations.AddField(
            model_name='postava',
            name='rodice',
            field=models.CharField(max_length=70, null=True, verbose_name='Rodiče'),
        ),
        migrations.AddField(
            model_name='postava',
            name='vyska',
            field=models.IntegerField(default=180, max_length=3, null=True, verbose_name='Výška'),
        ),
    ]
