# Generated by Django 3.0.5 on 2020-05-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloxov', '0013_auto_20200505_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanek',
            name='obrazek',
            field=models.FileField(null=True, upload_to='obrazky/'),
        ),
    ]
